<?php

/*******************************************************
NOTE: This is a cache file generated by IP.Board on Sun, 24 May 2015 13:54:57 +0000 by Guest
Do not translate this file as you will lose your translations next time you edit via the ACP
Please translate via the ACP
*******************************************************/



$lang = array( 
'mem_change_button' => "Изменить",
'mem_posts' => "Сообщения",
'm_overrride' => "Переопределить права группы следующими масками",
 ); 
