<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 24 May 2015 13:55:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_help_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['helpShowSection'] = array('notajax','isajax','notajax');
$this->_funcHooks['helpShowTopics'] = array('helpfiles');


}

/* -- helpShowSection --*/
function helpShowSection($one_text="",$two_text="",$three_text="", $text) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_help', $this->_funcHooks['helpShowSection'] ) )
{
$count_75911f9e97d6ebfeb3bd0d1bcd5ca2c8 = is_array($this->functionData['helpShowSection']) ? count($this->functionData['helpShowSection']) : 0;
$this->functionData['helpShowSection'][$count_75911f9e97d6ebfeb3bd0d1bcd5ca2c8]['one_text'] = $one_text;
$this->functionData['helpShowSection'][$count_75911f9e97d6ebfeb3bd0d1bcd5ca2c8]['two_text'] = $two_text;
$this->functionData['helpShowSection'][$count_75911f9e97d6ebfeb3bd0d1bcd5ca2c8]['three_text'] = $three_text;
$this->functionData['helpShowSection'][$count_75911f9e97d6ebfeb3bd0d1bcd5ca2c8]['text'] = $text;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- helpShowTopics --*/
function helpShowTopics($one_text="",$two_text="",$three_text="",$rows) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_help', $this->_funcHooks['helpShowTopics'] ) )
{
$count_d68797cd9cfd56579b67580faf944ba4 = is_array($this->functionData['helpShowTopics']) ? count($this->functionData['helpShowTopics']) : 0;
$this->functionData['helpShowTopics'][$count_d68797cd9cfd56579b67580faf944ba4]['one_text'] = $one_text;
$this->functionData['helpShowTopics'][$count_d68797cd9cfd56579b67580faf944ba4]['two_text'] = $two_text;
$this->functionData['helpShowTopics'][$count_d68797cd9cfd56579b67580faf944ba4]['three_text'] = $three_text;
$this->functionData['helpShowTopics'][$count_d68797cd9cfd56579b67580faf944ba4]['rows'] = $rows;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>