<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 24 May 2015 13:55:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_editors_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['ajaxEditBox'] = array('jsNotLoaded','ajaxerror','forceStd','showreason','appendedit','showappendedit','htmlstatus','showeditoptions');
$this->_funcHooks['editor'] = array('hasWrningInfo','jsNotLoaded','ismini','ismini','hasContent','hasType','ismini','hasHeight','hasMinimize','hasCallback','hasSaveKey','showEditor','hasToAcknowledge');
$this->_funcHooks['editorLoadJs'] = array('bypassCkEditor','hasimages','hasPastePlain');
$this->_funcHooks['mediaGenericWrapper'] = array('haswidth','hasheight','hasimage','hasdescription','genericmedia','hasrows');
$this->_funcHooks['sharedMedia'] = array('mediatabs');


}

/* -- ajaxEditBox --*/
function ajaxEditBox($post="", $pid=0, $error_msg="", $extraData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['ajaxEditBox'] ) )
{
$count_afa31096acf11ea3872def12f4488df2 = is_array($this->functionData['ajaxEditBox']) ? count($this->functionData['ajaxEditBox']) : 0;
$this->functionData['ajaxEditBox'][$count_afa31096acf11ea3872def12f4488df2]['post'] = $post;
$this->functionData['ajaxEditBox'][$count_afa31096acf11ea3872def12f4488df2]['pid'] = $pid;
$this->functionData['ajaxEditBox'][$count_afa31096acf11ea3872def12f4488df2]['error_msg'] = $error_msg;
$this->functionData['ajaxEditBox'][$count_afa31096acf11ea3872def12f4488df2]['extraData'] = $extraData;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editor --*/
function editor($formField='post', $content='', $options=array(), $autoSaveData=array(), $warningInfo='', $acknowledge=FALSE) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['editor'] ) )
{
$count_ac34de675ee9e5278ec339a8b841c8b3 = is_array($this->functionData['editor']) ? count($this->functionData['editor']) : 0;
$this->functionData['editor'][$count_ac34de675ee9e5278ec339a8b841c8b3]['formField'] = $formField;
$this->functionData['editor'][$count_ac34de675ee9e5278ec339a8b841c8b3]['content'] = $content;
$this->functionData['editor'][$count_ac34de675ee9e5278ec339a8b841c8b3]['options'] = $options;
$this->functionData['editor'][$count_ac34de675ee9e5278ec339a8b841c8b3]['autoSaveData'] = $autoSaveData;
$this->functionData['editor'][$count_ac34de675ee9e5278ec339a8b841c8b3]['warningInfo'] = $warningInfo;
$this->functionData['editor'][$count_ac34de675ee9e5278ec339a8b841c8b3]['acknowledge'] = $acknowledge;
}
$IPBHTML .= "<content><![CDATA[{$content}]]></content>";
return $IPBHTML;
}

/* -- editorLoadJs --*/
function editorLoadJs($options='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['editorLoadJs'] ) )
{
$count_38e93817af8b1c2f44986443967cd4c2 = is_array($this->functionData['editorLoadJs']) ? count($this->functionData['editorLoadJs']) : 0;
$this->functionData['editorLoadJs'][$count_38e93817af8b1c2f44986443967cd4c2]['options'] = $options;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editorSettings --*/
function editorSettings() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mediaGenericWrapper --*/
function mediaGenericWrapper($rows, $pages, $app, $plugin) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['mediaGenericWrapper'] ) )
{
$count_83e6269c11341056cade2be389520bec = is_array($this->functionData['mediaGenericWrapper']) ? count($this->functionData['mediaGenericWrapper']) : 0;
$this->functionData['mediaGenericWrapper'][$count_83e6269c11341056cade2be389520bec]['rows'] = $rows;
$this->functionData['mediaGenericWrapper'][$count_83e6269c11341056cade2be389520bec]['pages'] = $pages;
$this->functionData['mediaGenericWrapper'][$count_83e6269c11341056cade2be389520bec]['app'] = $app;
$this->functionData['mediaGenericWrapper'][$count_83e6269c11341056cade2be389520bec]['plugin'] = $plugin;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- sharedMedia --*/
function sharedMedia($tabs) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_editors', $this->_funcHooks['sharedMedia'] ) )
{
$count_007e947726629cb1cb871b299a36923a = is_array($this->functionData['sharedMedia']) ? count($this->functionData['sharedMedia']) : 0;
$this->functionData['sharedMedia'][$count_007e947726629cb1cb871b299a36923a]['tabs'] = $tabs;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- sharedMediaDefault --*/
function sharedMediaDefault() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>