<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 24 May 2015 13:55:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_modcp_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['deletedPosts'] = array('post_data','disablelightbox','hasPosts');
$this->_funcHooks['deletedTopics'] = array('hastopics');
$this->_funcHooks['editUserForm'] = array('editusercfielddesc','custom_fields','displaynamehistory','modPreview','postingRestricted','suspended','hasRestrictions','groupCanStatus','editusercfields');
$this->_funcHooks['latestWarnLogs'] = array('warningloop','haswarnings');
$this->_funcHooks['membersList'] = array('weAreSupmod','memberwarn','sendpm','blog','gallery','norep','posrep','negrep','repson','isnotbanned','isnotbanned2','members','showmembers');
$this->_funcHooks['membersModIPForm'] = array('modIpIe');
$this->_funcHooks['membersModIPFormMembers'] = array('ipMembers','modIPMembers');
$this->_funcHooks['membersModIPFormPosts'] = array('ipPosts','modFindMemberPosts');
$this->_funcHooks['modAnnounceForm'] = array('buttonlang','announceMessage','buttonlang');
$this->_funcHooks['modAnnouncements'] = array('announce_forums','notactive','notactive','announceHasForums','announceForum','announcements','hasAnnouncements');
$this->_funcHooks['modcpMessage'] = array('hasMessage');
$this->_funcHooks['modCPpost'] = array('reputation','noRep','posRep','negRep','repIgnored','postMid','postMember','postAdmin','postIp','postIsHardDeleted','canSoftDelete','canHardDelete','hasDeletedReasonRow','hasDeletedReason','showReason','postDeletedReason','isDeleted','canEdit','approveUnapprove','approvePost','canDelete','reportedPostData','isUnapproved','postEditByReason','postEditBy','reportedPostData');
$this->_funcHooks['modCPtopic'] = array('haslastpage','pages','isLink','isLinkEnd','multipages','hasStarterId','isntLink','hasDeletedReason','showReason','topicDeletedReason','replylang','isntLink3','tidRestoreLink','canHardDeleteLinkFromDb','topicIsHardDeleted','tidRestore','canHardDeleteFromDb','isntLink4','canSoftDelete','canHardDelete','topics');
$this->_funcHooks['overview'] = array('canEditMember');
$this->_funcHooks['portalPage'] = array('tabs','accessRC');
$this->_funcHooks['subTabLoop'] = array('subTabs','isMainTab','findTab');
$this->_funcHooks['unapprovedPosts'] = array('post_data','disablelightbox','hasPosts');
$this->_funcHooks['unapprovedTopics'] = array('hastopics');


}

/* -- deletedPosts --*/
function deletedPosts($posts, $other_data=array(), $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['deletedPosts'] ) )
{
$count_f02b8749c7d7cf09c41db6726b08d3d7 = is_array($this->functionData['deletedPosts']) ? count($this->functionData['deletedPosts']) : 0;
$this->functionData['deletedPosts'][$count_f02b8749c7d7cf09c41db6726b08d3d7]['posts'] = $posts;
$this->functionData['deletedPosts'][$count_f02b8749c7d7cf09c41db6726b08d3d7]['other_data'] = $other_data;
$this->functionData['deletedPosts'][$count_f02b8749c7d7cf09c41db6726b08d3d7]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- deletedTopics --*/
function deletedTopics($topics, $sdelete=array(), $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['deletedTopics'] ) )
{
$count_1dda1f004e580e286676aa9a6b720bae = is_array($this->functionData['deletedTopics']) ? count($this->functionData['deletedTopics']) : 0;
$this->functionData['deletedTopics'][$count_1dda1f004e580e286676aa9a6b720bae]['topics'] = $topics;
$this->functionData['deletedTopics'][$count_1dda1f004e580e286676aa9a6b720bae]['sdelete'] = $sdelete;
$this->functionData['deletedTopics'][$count_1dda1f004e580e286676aa9a6b720bae]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editUserForm --*/
function editUserForm($profile, $custom_fields=null) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['editUserForm'] ) )
{
$count_3fda06b21e3d2a74d5c9d3f75def843e = is_array($this->functionData['editUserForm']) ? count($this->functionData['editUserForm']) : 0;
$this->functionData['editUserForm'][$count_3fda06b21e3d2a74d5c9d3f75def843e]['profile'] = $profile;
$this->functionData['editUserForm'][$count_3fda06b21e3d2a74d5c9d3f75def843e]['custom_fields'] = $custom_fields;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inlineModIPMessage --*/
function inlineModIPMessage($msg='') {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- latestWarnLogs --*/
function latestWarnLogs($warnings, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['latestWarnLogs'] ) )
{
$count_5f654ac46fb0fc6a2ef439eaf6ff057a = is_array($this->functionData['latestWarnLogs']) ? count($this->functionData['latestWarnLogs']) : 0;
$this->functionData['latestWarnLogs'][$count_5f654ac46fb0fc6a2ef439eaf6ff057a]['warnings'] = $warnings;
$this->functionData['latestWarnLogs'][$count_5f654ac46fb0fc6a2ef439eaf6ff057a]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberLookup --*/
function memberLookup() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersList --*/
function membersList($type, $members, $pagelinks='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersList'] ) )
{
$count_27ee906b25ccae77477a0e7900f45137 = is_array($this->functionData['membersList']) ? count($this->functionData['membersList']) : 0;
$this->functionData['membersList'][$count_27ee906b25ccae77477a0e7900f45137]['type'] = $type;
$this->functionData['membersList'][$count_27ee906b25ccae77477a0e7900f45137]['members'] = $members;
$this->functionData['membersList'][$count_27ee906b25ccae77477a0e7900f45137]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPForm --*/
function membersModIPForm($ip="", $inlineMsg='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPForm'] ) )
{
$count_9fdd3b8f04cd9f31f8c18aa77cee707b = is_array($this->functionData['membersModIPForm']) ? count($this->functionData['membersModIPForm']) : 0;
$this->functionData['membersModIPForm'][$count_9fdd3b8f04cd9f31f8c18aa77cee707b]['ip'] = $ip;
$this->functionData['membersModIPForm'][$count_9fdd3b8f04cd9f31f8c18aa77cee707b]['inlineMsg'] = $inlineMsg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPFormMembers --*/
function membersModIPFormMembers($pages="",$members) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPFormMembers'] ) )
{
$count_2cbe6cb14176f60adc44eafda76e23a4 = is_array($this->functionData['membersModIPFormMembers']) ? count($this->functionData['membersModIPFormMembers']) : 0;
$this->functionData['membersModIPFormMembers'][$count_2cbe6cb14176f60adc44eafda76e23a4]['pages'] = $pages;
$this->functionData['membersModIPFormMembers'][$count_2cbe6cb14176f60adc44eafda76e23a4]['members'] = $members;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersModIPFormPosts --*/
function membersModIPFormPosts($count=0, $pageLinks='', $results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['membersModIPFormPosts'] ) )
{
$count_2b433462789c21cd1ca091ee54049a45 = is_array($this->functionData['membersModIPFormPosts']) ? count($this->functionData['membersModIPFormPosts']) : 0;
$this->functionData['membersModIPFormPosts'][$count_2b433462789c21cd1ca091ee54049a45]['count'] = $count;
$this->functionData['membersModIPFormPosts'][$count_2b433462789c21cd1ca091ee54049a45]['pageLinks'] = $pageLinks;
$this->functionData['membersModIPFormPosts'][$count_2b433462789c21cd1ca091ee54049a45]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modAnnounceForm --*/
function modAnnounceForm($announce,$forum_html,$type,$editor_html,$msg="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modAnnounceForm'] ) )
{
$count_333b709d13e6640e2b56222a804eeec7 = is_array($this->functionData['modAnnounceForm']) ? count($this->functionData['modAnnounceForm']) : 0;
$this->functionData['modAnnounceForm'][$count_333b709d13e6640e2b56222a804eeec7]['announce'] = $announce;
$this->functionData['modAnnounceForm'][$count_333b709d13e6640e2b56222a804eeec7]['forum_html'] = $forum_html;
$this->functionData['modAnnounceForm'][$count_333b709d13e6640e2b56222a804eeec7]['type'] = $type;
$this->functionData['modAnnounceForm'][$count_333b709d13e6640e2b56222a804eeec7]['editor_html'] = $editor_html;
$this->functionData['modAnnounceForm'][$count_333b709d13e6640e2b56222a804eeec7]['msg'] = $msg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modAnnouncements --*/
function modAnnouncements($announcements) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modAnnouncements'] ) )
{
$count_a3e767c4ee8ed00d99d370158f4c35de = is_array($this->functionData['modAnnouncements']) ? count($this->functionData['modAnnouncements']) : 0;
$this->functionData['modAnnouncements'][$count_a3e767c4ee8ed00d99d370158f4c35de]['announcements'] = $announcements;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modcpMessage --*/
function modcpMessage($message='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modcpMessage'] ) )
{
$count_17cdc5c3d30f5be07e78f70f0853b45e = is_array($this->functionData['modcpMessage']) ? count($this->functionData['modcpMessage']) : 0;
$this->functionData['modcpMessage'][$count_17cdc5c3d30f5be07e78f70f0853b45e]['message'] = $message;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- modCPpost --*/
function modCPpost($post, $displayData, $topic, $type) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modCPpost'] ) )
{
$count_1c4dff87723d36f11ae785ec2d2e061e = is_array($this->functionData['modCPpost']) ? count($this->functionData['modCPpost']) : 0;
$this->functionData['modCPpost'][$count_1c4dff87723d36f11ae785ec2d2e061e]['post'] = $post;
$this->functionData['modCPpost'][$count_1c4dff87723d36f11ae785ec2d2e061e]['displayData'] = $displayData;
$this->functionData['modCPpost'][$count_1c4dff87723d36f11ae785ec2d2e061e]['topic'] = $topic;
$this->functionData['modCPpost'][$count_1c4dff87723d36f11ae785ec2d2e061e]['type'] = $type;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- modCPtopic --*/
function modCPtopic($topics, $pagelinks, $type, $sdelete=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['modCPtopic'] ) )
{
$count_36b1b3b01774813be3799d981242421d = is_array($this->functionData['modCPtopic']) ? count($this->functionData['modCPtopic']) : 0;
$this->functionData['modCPtopic'][$count_36b1b3b01774813be3799d981242421d]['topics'] = $topics;
$this->functionData['modCPtopic'][$count_36b1b3b01774813be3799d981242421d]['pagelinks'] = $pagelinks;
$this->functionData['modCPtopic'][$count_36b1b3b01774813be3799d981242421d]['type'] = $type;
$this->functionData['modCPtopic'][$count_36b1b3b01774813be3799d981242421d]['sdelete'] = $sdelete;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- overview --*/
function overview() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['overview'] ) )
{
$count_941a2e8621e8eb1329fb9e7add1ae96f = is_array($this->functionData['overview']) ? count($this->functionData['overview']) : 0;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- portalPage --*/
function portalPage($output, $tabs=array(), $_activeNav=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['portalPage'] ) )
{
$count_377db45f5cfc78449c4f58229a42479f = is_array($this->functionData['portalPage']) ? count($this->functionData['portalPage']) : 0;
$this->functionData['portalPage'][$count_377db45f5cfc78449c4f58229a42479f]['output'] = $output;
$this->functionData['portalPage'][$count_377db45f5cfc78449c4f58229a42479f]['tabs'] = $tabs;
$this->functionData['portalPage'][$count_377db45f5cfc78449c4f58229a42479f]['_activeNav'] = $_activeNav;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- subTabLoop --*/
function subTabLoop() {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['subTabLoop'] ) )
{
$count_ec52520831cf084f54fe0ff54e46b823 = is_array($this->functionData['subTabLoop']) ? count($this->functionData['subTabLoop']) : 0;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- unapprovedPosts --*/
function unapprovedPosts($posts, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['unapprovedPosts'] ) )
{
$count_bcc7e62974359518f7e5e32c3c917912 = is_array($this->functionData['unapprovedPosts']) ? count($this->functionData['unapprovedPosts']) : 0;
$this->functionData['unapprovedPosts'][$count_bcc7e62974359518f7e5e32c3c917912]['posts'] = $posts;
$this->functionData['unapprovedPosts'][$count_bcc7e62974359518f7e5e32c3c917912]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- unapprovedTopics --*/
function unapprovedTopics($topics, $pagelinks) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_modcp', $this->_funcHooks['unapprovedTopics'] ) )
{
$count_f5eb1aa363294b30622d951767b3e3d8 = is_array($this->functionData['unapprovedTopics']) ? count($this->functionData['unapprovedTopics']) : 0;
$this->functionData['unapprovedTopics'][$count_f5eb1aa363294b30622d951767b3e3d8]['topics'] = $topics;
$this->functionData['unapprovedTopics'][$count_f5eb1aa363294b30622d951767b3e3d8]['pagelinks'] = $pagelinks;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>