<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 24 May 2015 13:55:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_other_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['ajaxPopUpNoPermission'] = array('msg');
$this->_funcHooks['displayBoardOffline'] = array('isGuest');
$this->_funcHooks['displayPopUpWindow'] = array('donotminifycss','cssImport','popupcssInline','popupmetaTags','popupjavascript','popuprss','popuprss','popupraw','popupdocumentHeadItems','popupheaditemtype','minifycss','csstominify','hasimportcss','popupcssinline','popupmetatags','popupminfiyrlhttpsp','popupminfiyrlhttpss','popupminfyjsrl','popupjsmodules','popuphttpsp','popuprl','popupjsmodules','popuphttpss','popuprl2','popupminifyjs','popupdocumenthead','popupbefriend','istm','istl','popupswfupload','popupfurl');
$this->_funcHooks['Error'] = array('haserrorcode','savedpost');
$this->_funcHooks['facebookPop'] = array('hasFbConnected');
$this->_funcHooks['generateTopicIcon'] = array('topicIsMoved','topicIsClosed','topicReadDot','topicUnreadDot','gotolatestwrap');
$this->_funcHooks['globalTemplateMinimal'] = array('fbcenabled','pagenumberintitle','isLargeTouch','isSmallTouch','mainpageContent','lastvisit','isfloat','sqldebuglink','closesqldebuglink','showdebuglevel');
$this->_funcHooks['inboxList'] = array('loopynotify','hasTopics');
$this->_funcHooks['likeMoreDialogue'] = array('hasVisibleEntries','hasAnonEntries');
$this->_funcHooks['likeSummaryContents'] = array('likeOnlyMembers');
$this->_funcHooks['notificationsList'] = array('loopynotify','hasnotifications','notifications');
$this->_funcHooks['questionAndAnswer'] = array('qadefault');
$this->_funcHooks['quickNavigationPanel'] = array('depth','important','innerAgain','hasTitle','linksisarray','outer');
$this->_funcHooks['quickNavigationWrapper'] = array('active','navTabs','isLargeTouch');
$this->_funcHooks['redirectTemplate'] = array('redirectcssImport','redirctcssInline','redirectjs','redirectrss','redirectrsd','redirectraw','redirectdocumentHeadItemsSub','redirectdocumentHeadItems','redirectfull','redirectcssimport','redirectcssinline','redirectdh','redirectmozfull','redirectlink');
$this->_funcHooks['repButtons'] = array('hasNoLikes','giveRepUp','giveRepDown','canGiveRep','pos','giveRepUp','giveRepDown','canGiveRep','hasNoRep','hasPosRep','hasNegRep','isNotLike','isLike','canRep','reputationBox','giveRepUp','canGiveRep','canGiveRep','giveRepDown','isLike','canRep');
$this->_funcHooks['socialSharePostStrip'] = array('canShareThis','services','canSave','canShare');
$this->_funcHooks['tagCloud'] = array('eachTag');
$this->_funcHooks['tagEntry'] = array('noClass','inSearch','inSearchSub','hasSearchSection');
$this->_funcHooks['tagPrefix'] = array('inSearch','inSearchSub','hasSearchSection');
$this->_funcHooks['tagTextEntryBox'] = array('isClosedField','prefixChecked','canPrefix');


}

/* -- ajaxPopUpNoPermission --*/
function ajaxPopUpNoPermission($msg='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['ajaxPopUpNoPermission'] ) )
{
$count_0b3d56502c2f0ab2eb0ddba24750cf26 = is_array($this->functionData['ajaxPopUpNoPermission']) ? count($this->functionData['ajaxPopUpNoPermission']) : 0;
$this->functionData['ajaxPopUpNoPermission'][$count_0b3d56502c2f0ab2eb0ddba24750cf26]['msg'] = $msg;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- captchaGD --*/
function captchaGD($captcha_unique_id) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- captchaKeycaptcha --*/
function captchaKeycaptcha($challenge="") {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- captchaRecaptcha --*/
function captchaRecaptcha($html="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayBoardOffline --*/
function displayBoardOffline($message="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['displayBoardOffline'] ) )
{
$count_c30cd7baff1165ae5dc98d644213b5f9 = is_array($this->functionData['displayBoardOffline']) ? count($this->functionData['displayBoardOffline']) : 0;
$this->functionData['displayBoardOffline'][$count_c30cd7baff1165ae5dc98d644213b5f9]['message'] = $message;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayPopUpWindow --*/
function displayPopUpWindow($documentHeadItems, $css, $jsLoaderItems, $title="", $output="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['displayPopUpWindow'] ) )
{
$count_ac63a511b3341ae535abcce044bd4e4a = is_array($this->functionData['displayPopUpWindow']) ? count($this->functionData['displayPopUpWindow']) : 0;
$this->functionData['displayPopUpWindow'][$count_ac63a511b3341ae535abcce044bd4e4a]['documentHeadItems'] = $documentHeadItems;
$this->functionData['displayPopUpWindow'][$count_ac63a511b3341ae535abcce044bd4e4a]['css'] = $css;
$this->functionData['displayPopUpWindow'][$count_ac63a511b3341ae535abcce044bd4e4a]['jsLoaderItems'] = $jsLoaderItems;
$this->functionData['displayPopUpWindow'][$count_ac63a511b3341ae535abcce044bd4e4a]['title'] = $title;
$this->functionData['displayPopUpWindow'][$count_ac63a511b3341ae535abcce044bd4e4a]['output'] = $output;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- Error --*/
function Error($message="",$code=0,$ad_email_one="",$ad_email_two="", $title="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['Error'] ) )
{
$count_8e10db61c3f6862719ee4bd591c4487a = is_array($this->functionData['Error']) ? count($this->functionData['Error']) : 0;
$this->functionData['Error'][$count_8e10db61c3f6862719ee4bd591c4487a]['message'] = $message;
$this->functionData['Error'][$count_8e10db61c3f6862719ee4bd591c4487a]['code'] = $code;
$this->functionData['Error'][$count_8e10db61c3f6862719ee4bd591c4487a]['ad_email_one'] = $ad_email_one;
$this->functionData['Error'][$count_8e10db61c3f6862719ee4bd591c4487a]['ad_email_two'] = $ad_email_two;
$this->functionData['Error'][$count_8e10db61c3f6862719ee4bd591c4487a]['title'] = $title;
}
$IPBHTML .= "<error>{$message}</error>";
return $IPBHTML;
}

/* -- facebookDone --*/
function facebookDone($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- facebookPop --*/
function facebookPop($user=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['facebookPop'] ) )
{
$count_8e6c013b42a09034f8f83bbdc66ffdce = is_array($this->functionData['facebookPop']) ? count($this->functionData['facebookPop']) : 0;
$this->functionData['facebookPop'][$count_8e6c013b42a09034f8f83bbdc66ffdce]['user'] = $user;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followUnsubscribe --*/
function followUnsubscribe($data, $meta) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- generateTopicIcon --*/
function generateTopicIcon($imgArray, $unreadUrl) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['generateTopicIcon'] ) )
{
$count_0e8de74ee613a225e34d18bdeddf9dac = is_array($this->functionData['generateTopicIcon']) ? count($this->functionData['generateTopicIcon']) : 0;
$this->functionData['generateTopicIcon'][$count_0e8de74ee613a225e34d18bdeddf9dac]['imgArray'] = $imgArray;
$this->functionData['generateTopicIcon'][$count_0e8de74ee613a225e34d18bdeddf9dac]['unreadUrl'] = $unreadUrl;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- globalTemplateMinimal --*/
function globalTemplateMinimal($html, $documentHeadItems, $css, $jsModules, $metaTags, array $header_items, $items=array(), $footer_items=array(), $stats=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['globalTemplateMinimal'] ) )
{
$count_96d63f963f6ae823ed354e53336dd015 = is_array($this->functionData['globalTemplateMinimal']) ? count($this->functionData['globalTemplateMinimal']) : 0;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['html'] = $html;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['documentHeadItems'] = $documentHeadItems;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['css'] = $css;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['jsModules'] = $jsModules;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['metaTags'] = $metaTags;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['header_items'] = $header_items;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['items'] = $items;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['footer_items'] = $footer_items;
$this->functionData['globalTemplateMinimal'][$count_96d63f963f6ae823ed354e53336dd015]['stats'] = $stats;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inboxList --*/
function inboxList($topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['inboxList'] ) )
{
$count_cb104b5e9af7dfdedb43803abaa4d722 = is_array($this->functionData['inboxList']) ? count($this->functionData['inboxList']) : 0;
$this->functionData['inboxList'][$count_cb104b5e9af7dfdedb43803abaa4d722]['topics'] = $topics;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- inlineUploaderComplete --*/
function inlineUploaderComplete($json) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeMoreDialogue --*/
function likeMoreDialogue($data, $relId, $cache) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['likeMoreDialogue'] ) )
{
$count_9bc602c4fd7de6cf2124d946dc06e617 = is_array($this->functionData['likeMoreDialogue']) ? count($this->functionData['likeMoreDialogue']) : 0;
$this->functionData['likeMoreDialogue'][$count_9bc602c4fd7de6cf2124d946dc06e617]['data'] = $data;
$this->functionData['likeMoreDialogue'][$count_9bc602c4fd7de6cf2124d946dc06e617]['relId'] = $relId;
$this->functionData['likeMoreDialogue'][$count_9bc602c4fd7de6cf2124d946dc06e617]['cache'] = $cache;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSetDialogue --*/
function likeSetDialogue($app, $area, $relid, $data) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSummary --*/
function likeSummary($data, $relId, $opts) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- likeSummaryContents --*/
function likeSummaryContents($data, $relId, $opts=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['likeSummaryContents'] ) )
{
$count_137f19dc2fd655e462d44573a9d0c0d0 = is_array($this->functionData['likeSummaryContents']) ? count($this->functionData['likeSummaryContents']) : 0;
$this->functionData['likeSummaryContents'][$count_137f19dc2fd655e462d44573a9d0c0d0]['data'] = $data;
$this->functionData['likeSummaryContents'][$count_137f19dc2fd655e462d44573a9d0c0d0]['relId'] = $relId;
$this->functionData['likeSummaryContents'][$count_137f19dc2fd655e462d44573a9d0c0d0]['opts'] = $opts;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- notificationsList --*/
function notificationsList($notifications) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['notificationsList'] ) )
{
$count_434c3e7faddada9bee9c7ac4cab66377 = is_array($this->functionData['notificationsList']) ? count($this->functionData['notificationsList']) : 0;
$this->functionData['notificationsList'][$count_434c3e7faddada9bee9c7ac4cab66377]['notifications'] = $notifications;
}
$IPBHTML .= "<template>popoverNotifications</template>
<notifications>
	".$this->__f__98ad3be04825532b7af7b8653b174dd2($notifications)."</notifications>";
return $IPBHTML;
}


function __f__98ad3be04825532b7af7b8653b174dd2($notifications)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $notifications as $notification )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<notification>
			<id>{$notification['notify_id']}</id>
			<url><![CDATA[{$notification['notify_url']}]]></url>
			<icon><![CDATA[{$notification['member']['pp_thumb_photo']}]]></icon>
			<text><![CDATA[{$notification['notify_title']}]]></text>
		</notification>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- privacyPolicy --*/
function privacyPolicy($title, $text) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- questionAndAnswer --*/
function questionAndAnswer($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['questionAndAnswer'] ) )
{
$count_d28f53f44dc1519ae16344e6dee48045 = is_array($this->functionData['questionAndAnswer']) ? count($this->functionData['questionAndAnswer']) : 0;
$this->functionData['questionAndAnswer'][$count_d28f53f44dc1519ae16344e6dee48045]['data'] = $data;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationOffline --*/
function quickNavigationOffline($message) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationPanel --*/
function quickNavigationPanel($data=array(), $currentApp='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['quickNavigationPanel'] ) )
{
$count_d9c4b7db7ec816d3aa17e28366e43164 = is_array($this->functionData['quickNavigationPanel']) ? count($this->functionData['quickNavigationPanel']) : 0;
$this->functionData['quickNavigationPanel'][$count_d9c4b7db7ec816d3aa17e28366e43164]['data'] = $data;
$this->functionData['quickNavigationPanel'][$count_d9c4b7db7ec816d3aa17e28366e43164]['currentApp'] = $currentApp;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- quickNavigationWrapper --*/
function quickNavigationWrapper($tabs=array(), $data=array(), $currentApp='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['quickNavigationWrapper'] ) )
{
$count_4d2d1dbb9c9caca2d5f9ab9b4e5ef36c = is_array($this->functionData['quickNavigationWrapper']) ? count($this->functionData['quickNavigationWrapper']) : 0;
$this->functionData['quickNavigationWrapper'][$count_4d2d1dbb9c9caca2d5f9ab9b4e5ef36c]['tabs'] = $tabs;
$this->functionData['quickNavigationWrapper'][$count_4d2d1dbb9c9caca2d5f9ab9b4e5ef36c]['data'] = $data;
$this->functionData['quickNavigationWrapper'][$count_4d2d1dbb9c9caca2d5f9ab9b4e5ef36c]['currentApp'] = $currentApp;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- redirectTemplate --*/
function redirectTemplate($documentHeadItems, $css, $jsLoaderItems, $text="",$url="", $full=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['redirectTemplate'] ) )
{
$count_c74f8a9fc9d265597d6b54ef67bb9811 = is_array($this->functionData['redirectTemplate']) ? count($this->functionData['redirectTemplate']) : 0;
$this->functionData['redirectTemplate'][$count_c74f8a9fc9d265597d6b54ef67bb9811]['documentHeadItems'] = $documentHeadItems;
$this->functionData['redirectTemplate'][$count_c74f8a9fc9d265597d6b54ef67bb9811]['css'] = $css;
$this->functionData['redirectTemplate'][$count_c74f8a9fc9d265597d6b54ef67bb9811]['jsLoaderItems'] = $jsLoaderItems;
$this->functionData['redirectTemplate'][$count_c74f8a9fc9d265597d6b54ef67bb9811]['text'] = $text;
$this->functionData['redirectTemplate'][$count_c74f8a9fc9d265597d6b54ef67bb9811]['url'] = $url;
$this->functionData['redirectTemplate'][$count_c74f8a9fc9d265597d6b54ef67bb9811]['full'] = $full;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- repButtons --*/
function repButtons($member, $data=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['repButtons'] ) )
{
$count_4b8e112257212d453bfa5274544e5f1a = is_array($this->functionData['repButtons']) ? count($this->functionData['repButtons']) : 0;
$this->functionData['repButtons'][$count_4b8e112257212d453bfa5274544e5f1a]['member'] = $member;
$this->functionData['repButtons'][$count_4b8e112257212d453bfa5274544e5f1a]['data'] = $data;
}
$IPBHTML .= "" . ((!( $this->settings['reputation_protected_groups'] && in_array( $member['member_group_id'], explode( ',', $this->settings['reputation_protected_groups'] ) ) ) and $this->memberData['member_id']) ? ("" . (($this->settings['reputation_point_types'] == 'like') ? ("" . ((IPSMember::canGiveRep( $data, $member ) !== false) ? ("" . ((IPSMember::canRepUp( $data, $member ) !== false) ? ("
				<likeURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></likeURL>
			") : ("")) . "") : ("")) . "") : ("" . ((IPSMember::canGiveRep( $data, $member ) !== false) ? ("
			<repupURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></repupURL>
		") : ("")) . "
		" . ((IPSMember::canRepDown( $data, $member ) !== false) ? ("
			<repDownURL><![CDATA[{$this->settings['base_url']}app=core&amp;module=global&amp;section=reputation&amp;do=add_rating&amp;app_rate={$data['app']}&amp;type={$data['type']}&amp;type_id={$data['primaryId']}&amp;rating=-1&amp;secure_key={$this->member->form_hash}&amp;post_return={$data['primaryId']}]]></repDownURL>
		") : ("")) . "")) . "") : ("")) . "";
return $IPBHTML;
}

/* -- repMoreDialogue --*/
function repMoreDialogue($data, $relId) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- reputationPopup --*/
function reputationPopup($reps) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- socialSharePostStrip --*/
function socialSharePostStrip($id=null) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['socialSharePostStrip'] ) )
{
$count_8c9c1bd22fc4e621def593538e073d70 = is_array($this->functionData['socialSharePostStrip']) ? count($this->functionData['socialSharePostStrip']) : 0;
$this->functionData['socialSharePostStrip'][$count_8c9c1bd22fc4e621def593538e073d70]['id'] = $id;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tagCloud --*/
function tagCloud($tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagCloud'] ) )
{
$count_faf197e5ccd46a9afd27932afc945dba = is_array($this->functionData['tagCloud']) ? count($this->functionData['tagCloud']) : 0;
$this->functionData['tagCloud'][$count_faf197e5ccd46a9afd27932afc945dba]['tags'] = $tags;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagEntry --*/
function tagEntry($tag, $noClass=false, $app='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagEntry'] ) )
{
$count_d87e907287d3d8ec3e38fbed7ad4a54e = is_array($this->functionData['tagEntry']) ? count($this->functionData['tagEntry']) : 0;
$this->functionData['tagEntry'][$count_d87e907287d3d8ec3e38fbed7ad4a54e]['tag'] = $tag;
$this->functionData['tagEntry'][$count_d87e907287d3d8ec3e38fbed7ad4a54e]['noClass'] = $noClass;
$this->functionData['tagEntry'][$count_d87e907287d3d8ec3e38fbed7ad4a54e]['app'] = $app;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagPrefix --*/
function tagPrefix($tag, $app='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagPrefix'] ) )
{
$count_a49a6a45c3f145a083d0e562dae48ef0 = is_array($this->functionData['tagPrefix']) ? count($this->functionData['tagPrefix']) : 0;
$this->functionData['tagPrefix'][$count_a49a6a45c3f145a083d0e562dae48ef0]['tag'] = $tag;
$this->functionData['tagPrefix'][$count_a49a6a45c3f145a083d0e562dae48ef0]['app'] = $app;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- tagsAsPopUp --*/
function tagsAsPopUp($tags) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- tagTextEntryBox --*/
function tagTextEntryBox($tags, $options, $where) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_other', $this->_funcHooks['tagTextEntryBox'] ) )
{
$count_e73a67ddc1c64d8216606863a61925c4 = is_array($this->functionData['tagTextEntryBox']) ? count($this->functionData['tagTextEntryBox']) : 0;
$this->functionData['tagTextEntryBox'][$count_e73a67ddc1c64d8216606863a61925c4]['tags'] = $tags;
$this->functionData['tagTextEntryBox'][$count_e73a67ddc1c64d8216606863a61925c4]['options'] = $options;
$this->functionData['tagTextEntryBox'][$count_e73a67ddc1c64d8216606863a61925c4]['where'] = $where;
}
$IPBHTML .= "<tagSystemIsEnabled>{$options['isEnabled']}</tagSystemIsEnabled>
<tagSystemIsOpen>{$options['isOpenSystem']}</tagSystemIsOpen>
<prefixesEnabled>{$options['prefixesEnabled']}</prefixesEnabled>
<predefinedTags>
</predefinedTags>";
return $IPBHTML;
}

/* -- twitterDone --*/
function twitterDone($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- twitterPop --*/
function twitterPop($user) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>