<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 24 May 2015 13:55:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_search_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['asForumPosts'] = array('notLastFtAsForum','topicsForumTrail','moderated','postMid','postModSelected','postModCheckbox','postMember','hasForumTrail');
$this->_funcHooks['asForumTopics'] = array('notLastFtAsForum','topicsForumTrail','haslastpage','pages','archivedBadge','hasPrefix','resultIsPostTR','isNewPostTR','hasTags','multipages','bothSearchUnderTitle','isFollowedStuff','replylang','bothSearch','forumsDigests','isArchivedCb','isAdmin','isFollowedStuff','notLastFtAsForum','topicsForumTrail','resultIsPostAsForum','isNewPostAsForum');
$this->_funcHooks['followData'] = array('hasFrequence','isAnonymous');
$this->_funcHooks['followedContentForumsWrapper'] = array('NCresultsAsForum');
$this->_funcHooks['followedContentForumsWrapperForums'] = array('showSubForumsLit','subforums','showSubForums','isFollowedStuff','hasphoto','lastPosterID','hideDateUrl','hasLastTopicId','hideLastInfo','forumsDigests','NCresultsAsForum');
$this->_funcHooks['followedContentView'] = array('appIsSearched','supportsLikes','apps','hasconfirm','haslikeserror','forumsTab','memberFollow','membersTab','memberFollow','searchedApp','forumsDigests','hasLikeForMod','NPTotal');
$this->_funcHooks['forumAdvancedSearchFilters'] = array('hasArchives');
$this->_funcHooks['forumsVncFilters'] = array('hasFiltersSet','depth','hasFiltersSet','hasTitle','forumlist','noFiltersSet','noFiltersSet');
$this->_funcHooks['helpSearchResult'] = array('showHelpContent');
$this->_funcHooks['memberCommentsSearchResult'] = array('isUpdate','hasMore','maxReplies');
$this->_funcHooks['newContentView'] = array('appIsSearched','appIsSearchable','apps','forumsTab','membersTab','helpTab','hazVNC','hazMember','checked','userModeAll','userModeTitle','hasFilters','vncFilterForumsOnly','canFollowFilter','searchismod','NPTotal');
$this->_funcHooks['searchAdvancedForm'] = array('appLoop','calendarlocale','searchTermsRemoved','searchError','isFullText','tagyouareit');
$this->_funcHooks['searchResults'] = array('subResult','results','hasResults','subResult','results');
$this->_funcHooks['searchResultsAsForum'] = array('NCresultsAsForum','asTawpiks','asPostsStart','asPostsEnd','isAdminBottom','isAdmin','disablelightbox','asTawpiks2');
$this->_funcHooks['searchResultsWrapper'] = array('appIsSearched','appIsSearchable','apps','hasSearchResultsCut','hasSearchResultsTags','hasSearchResults','forumsTab','membersTab','helpTab','searchismod','noResultsTerm','hasTotal');
$this->_funcHooks['searchRowGenericFormat'] = array('showGenericContent','isUpdated','hasMemberId','isUpdatedOrHasMemberId');
$this->_funcHooks['topicPostSearchResultAsForum'] = array('whichWayToGo');
$this->_funcHooks['userPostsView'] = array('appIsSearched','appIsSearchable','apps','NPhasResults','forumsTab','membersTab','helpTab','searchismod','NPTotal');


}

/* -- asForumPosts --*/
function asForumPosts($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['asForumPosts'] ) )
{
$count_898145b9872e1b4107230997c4a64c77 = is_array($this->functionData['asForumPosts']) ? count($this->functionData['asForumPosts']) : 0;
$this->functionData['asForumPosts'][$count_898145b9872e1b4107230997c4a64c77]['data'] = $data;
}
$IPBHTML .= "<template>searchResultsAsPost</template>
<searchResults>
</searchResults>";
return $IPBHTML;
}

/* -- asForumTopics --*/
function asForumTopics($data) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['asForumTopics'] ) )
{
$count_5d3b159f64d27d00d43c56d8d93f8f39 = is_array($this->functionData['asForumTopics']) ? count($this->functionData['asForumTopics']) : 0;
$this->functionData['asForumTopics'][$count_5d3b159f64d27d00d43c56d8d93f8f39]['data'] = $data;
}
$IPBHTML .= "<searchResult>
	<tid>{$data['tid']}</tid>
	<title>{$data['_shortTitle']}</title>
	<state>{$data['state']}</state>
	<url>" . (($data['_unreadUrl']) ? ("{$data['_unreadUrl']}") : ("" . $this->registry->getClass('output')->formatUrl( $this->registry->getClass('output')->buildUrl( "showtopic={$data['type_id_2']}&amp;view=" . (($this->request['do']=='new_posts' OR $this->request['do']=='active') ? ("getnewpost") : ("" . (($data['misc']) ? ("findpost&amp;p={$data['misc']}") : ("")) . "")) . "&amp;hl={$this->request['search_higlight']}&amp;fromsearch=1", "public",'' ), "{$data['title_seo']}", "showtopic" ) . "")) . "</url>
	<isRead>" . (($data['_isRead'] == 1) ? ("1") : ("0")) . "</isRead>
	<authorid>{$data['author_id']}</authorid>
	<author>{$data['author_name']}</author>
	".$this->__f__4bc7b1527c699643380de940c88a0f4c($data)."</searchResult>";
return $IPBHTML;
}


function __f__4bc7b1527c699643380de940c88a0f4c($data)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $data['_forum_trail'] as $i => $f )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "" . (($i+1 == count( $data['_forum_trail'] )) ? ("<forum>{$f[0]}</forum>") : ("")) . "
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- followData --*/
function followData($followData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followData'] ) )
{
$count_337716ef573acf465f33f18548bba91f = is_array($this->functionData['followData']) ? count($this->functionData['followData']) : 0;
$this->functionData['followData'][$count_337716ef573acf465f33f18548bba91f]['followData'] = $followData;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapper --*/
function followedContentForumsWrapper($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentForumsWrapper'] ) )
{
$count_e2f6a9a5e3c33a1543778ef2b60d8990 = is_array($this->functionData['followedContentForumsWrapper']) ? count($this->functionData['followedContentForumsWrapper']) : 0;
$this->functionData['followedContentForumsWrapper'][$count_e2f6a9a5e3c33a1543778ef2b60d8990]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentForumsWrapperForums --*/
function followedContentForumsWrapperForums($results) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentForumsWrapperForums'] ) )
{
$count_0813a11d8e8a2035976b8ab115db4347 = is_array($this->functionData['followedContentForumsWrapperForums']) ? count($this->functionData['followedContentForumsWrapperForums']) : 0;
$this->functionData['followedContentForumsWrapperForums'][$count_0813a11d8e8a2035976b8ab115db4347]['results'] = $results;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- followedContentView --*/
function followedContentView($results, $pagination, $total, $error, $contentTypes) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['followedContentView'] ) )
{
$count_dbf44a8e7f2d791ef158e3c6fe1c9f90 = is_array($this->functionData['followedContentView']) ? count($this->functionData['followedContentView']) : 0;
$this->functionData['followedContentView'][$count_dbf44a8e7f2d791ef158e3c6fe1c9f90]['results'] = $results;
$this->functionData['followedContentView'][$count_dbf44a8e7f2d791ef158e3c6fe1c9f90]['pagination'] = $pagination;
$this->functionData['followedContentView'][$count_dbf44a8e7f2d791ef158e3c6fe1c9f90]['total'] = $total;
$this->functionData['followedContentView'][$count_dbf44a8e7f2d791ef158e3c6fe1c9f90]['error'] = $error;
$this->functionData['followedContentView'][$count_dbf44a8e7f2d791ef158e3c6fe1c9f90]['contentTypes'] = $contentTypes;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumAdvancedSearchFilters --*/
function forumAdvancedSearchFilters($forums, $archivedPostCount=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['forumAdvancedSearchFilters'] ) )
{
$count_7e5640ba5ded7851eefef0ba4af137e9 = is_array($this->functionData['forumAdvancedSearchFilters']) ? count($this->functionData['forumAdvancedSearchFilters']) : 0;
$this->functionData['forumAdvancedSearchFilters'][$count_7e5640ba5ded7851eefef0ba4af137e9]['forums'] = $forums;
$this->functionData['forumAdvancedSearchFilters'][$count_7e5640ba5ded7851eefef0ba4af137e9]['archivedPostCount'] = $archivedPostCount;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- forumsVncFilters --*/
function forumsVncFilters($data, $currentPrefs) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['forumsVncFilters'] ) )
{
$count_7e407382ecaf70a0e43a4355854bc6fb = is_array($this->functionData['forumsVncFilters']) ? count($this->functionData['forumsVncFilters']) : 0;
$this->functionData['forumsVncFilters'][$count_7e407382ecaf70a0e43a4355854bc6fb]['data'] = $data;
$this->functionData['forumsVncFilters'][$count_7e407382ecaf70a0e43a4355854bc6fb]['currentPrefs'] = $currentPrefs;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- helpSearchResult --*/
function helpSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['helpSearchResult'] ) )
{
$count_816d900c8571d2fffb135b2046e203ce = is_array($this->functionData['helpSearchResult']) ? count($this->functionData['helpSearchResult']) : 0;
$this->functionData['helpSearchResult'][$count_816d900c8571d2fffb135b2046e203ce]['r'] = $r;
$this->functionData['helpSearchResult'][$count_816d900c8571d2fffb135b2046e203ce]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberCommentsSearchResult --*/
function memberCommentsSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['memberCommentsSearchResult'] ) )
{
$count_0924c8c08c503b98bd82df7086d9f832 = is_array($this->functionData['memberCommentsSearchResult']) ? count($this->functionData['memberCommentsSearchResult']) : 0;
$this->functionData['memberCommentsSearchResult'][$count_0924c8c08c503b98bd82df7086d9f832]['r'] = $r;
$this->functionData['memberCommentsSearchResult'][$count_0924c8c08c503b98bd82df7086d9f832]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- memberSearchResult --*/
function memberSearchResult($r, $resultAsTitle=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- newContentView --*/
function newContentView($results, $pagination, $total, $sortDropDown, $sortIn, $dateCutSet=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['newContentView'] ) )
{
$count_3fc6b21d64aa3d37bd55b24258994a06 = is_array($this->functionData['newContentView']) ? count($this->functionData['newContentView']) : 0;
$this->functionData['newContentView'][$count_3fc6b21d64aa3d37bd55b24258994a06]['results'] = $results;
$this->functionData['newContentView'][$count_3fc6b21d64aa3d37bd55b24258994a06]['pagination'] = $pagination;
$this->functionData['newContentView'][$count_3fc6b21d64aa3d37bd55b24258994a06]['total'] = $total;
$this->functionData['newContentView'][$count_3fc6b21d64aa3d37bd55b24258994a06]['sortDropDown'] = $sortDropDown;
$this->functionData['newContentView'][$count_3fc6b21d64aa3d37bd55b24258994a06]['sortIn'] = $sortIn;
$this->functionData['newContentView'][$count_3fc6b21d64aa3d37bd55b24258994a06]['dateCutSet'] = $dateCutSet;
}
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchAdvancedForm --*/
function searchAdvancedForm($filters='', $msg='', $current_app, $removed_search_terms=array(), $isFT=false, $canTag=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchAdvancedForm'] ) )
{
$count_021c4e45173b443c0d99e2f9d411a2ee = is_array($this->functionData['searchAdvancedForm']) ? count($this->functionData['searchAdvancedForm']) : 0;
$this->functionData['searchAdvancedForm'][$count_021c4e45173b443c0d99e2f9d411a2ee]['filters'] = $filters;
$this->functionData['searchAdvancedForm'][$count_021c4e45173b443c0d99e2f9d411a2ee]['msg'] = $msg;
$this->functionData['searchAdvancedForm'][$count_021c4e45173b443c0d99e2f9d411a2ee]['current_app'] = $current_app;
$this->functionData['searchAdvancedForm'][$count_021c4e45173b443c0d99e2f9d411a2ee]['removed_search_terms'] = $removed_search_terms;
$this->functionData['searchAdvancedForm'][$count_021c4e45173b443c0d99e2f9d411a2ee]['isFT'] = $isFT;
$this->functionData['searchAdvancedForm'][$count_021c4e45173b443c0d99e2f9d411a2ee]['canTag'] = $canTag;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- searchResults --*/
function searchResults($results, $titlesOnly) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResults'] ) )
{
$count_b492c2c91cca0aea571baacf846b1ff0 = is_array($this->functionData['searchResults']) ? count($this->functionData['searchResults']) : 0;
$this->functionData['searchResults'][$count_b492c2c91cca0aea571baacf846b1ff0]['results'] = $results;
$this->functionData['searchResults'][$count_b492c2c91cca0aea571baacf846b1ff0]['titlesOnly'] = $titlesOnly;
}
$IPBHTML .= "" . ((is_array( $results )) ? ("".$this->__f__71f084dfd12354378d5d1b98e4495ab6($results,$titlesOnly)."		") : ("")) . "";
return $IPBHTML;
}


function __f__71f084dfd12354378d5d1b98e4495ab6($results, $titlesOnly)
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $results as $result )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
			" . (($result['sub']) ? ("
					{$result['html']}
				
			") : ("
					{$result['html']}
				
			")) . "
		
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- searchResultsAsForum --*/
function searchResultsAsForum($results, $titlesOnly) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResultsAsForum'] ) )
{
$count_0a14f6059f05813e0b83a6a8165610ea = is_array($this->functionData['searchResultsAsForum']) ? count($this->functionData['searchResultsAsForum']) : 0;
$this->functionData['searchResultsAsForum'][$count_0a14f6059f05813e0b83a6a8165610ea]['results'] = $results;
$this->functionData['searchResultsAsForum'][$count_0a14f6059f05813e0b83a6a8165610ea]['titlesOnly'] = $titlesOnly;
}
$IPBHTML .= "<template>searchResultsAsTopic</template>
<searchResults>
" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'searchResults' ) ? $this->registry->getClass('output')->getTemplate('search')->searchResults($results, $titlesOnly) : '' ) . "
</searchResults>";
return $IPBHTML;
}

/* -- searchResultsWrapper --*/
function searchResultsWrapper($results, $sortDropDown, $sortIn, $pagination, $total, $showing, $search_term, $url_string, $current_key, $removed_search_terms=array(), $limited=0, $wasLimited=false, $search_tags) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchResultsWrapper'] ) )
{
$count_94b86ba11ea170e79bab72f0c9db8bdd = is_array($this->functionData['searchResultsWrapper']) ? count($this->functionData['searchResultsWrapper']) : 0;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['results'] = $results;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['sortDropDown'] = $sortDropDown;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['sortIn'] = $sortIn;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['pagination'] = $pagination;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['total'] = $total;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['showing'] = $showing;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['search_term'] = $search_term;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['url_string'] = $url_string;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['current_key'] = $current_key;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['removed_search_terms'] = $removed_search_terms;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['limited'] = $limited;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['wasLimited'] = $wasLimited;
$this->functionData['searchResultsWrapper'][$count_94b86ba11ea170e79bab72f0c9db8bdd]['search_tags'] = $search_tags;
}
$IPBHTML .= "{$results}";
return $IPBHTML;
}

/* -- searchRowGenericFormat --*/
function searchRowGenericFormat($r, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['searchRowGenericFormat'] ) )
{
$count_2251ac2b6fb034b8509789109491072d = is_array($this->functionData['searchRowGenericFormat']) ? count($this->functionData['searchRowGenericFormat']) : 0;
$this->functionData['searchRowGenericFormat'][$count_2251ac2b6fb034b8509789109491072d]['r'] = $r;
$this->functionData['searchRowGenericFormat'][$count_2251ac2b6fb034b8509789109491072d]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topicPostSearchResultAsForum --*/
function topicPostSearchResultAsForum($data, $resultAsTitle=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['topicPostSearchResultAsForum'] ) )
{
$count_d016dd06c0eea0f5c6a5523b691bb2b0 = is_array($this->functionData['topicPostSearchResultAsForum']) ? count($this->functionData['topicPostSearchResultAsForum']) : 0;
$this->functionData['topicPostSearchResultAsForum'][$count_d016dd06c0eea0f5c6a5523b691bb2b0]['data'] = $data;
$this->functionData['topicPostSearchResultAsForum'][$count_d016dd06c0eea0f5c6a5523b691bb2b0]['resultAsTitle'] = $resultAsTitle;
}
$IPBHTML .= "" . ( method_exists( $this->registry->getClass('output')->getTemplate('search'), 'asForumTopics' ) ? $this->registry->getClass('output')->getTemplate('search')->asForumTopics($data) : '' ) . "";
return $IPBHTML;
}

/* -- userPostsView --*/
function userPostsView($results, $pagination, $total, $member, $limited=0, $wasLimited=false, $beginTime=0, $sortIn=null, $sortDropDown=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_search', $this->_funcHooks['userPostsView'] ) )
{
$count_2e1af8fdabbd81bc0bad2cbd1c1de161 = is_array($this->functionData['userPostsView']) ? count($this->functionData['userPostsView']) : 0;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['results'] = $results;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['pagination'] = $pagination;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['total'] = $total;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['member'] = $member;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['limited'] = $limited;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['wasLimited'] = $wasLimited;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['beginTime'] = $beginTime;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['sortIn'] = $sortIn;
$this->functionData['userPostsView'][$count_2e1af8fdabbd81bc0bad2cbd1c1de161]['sortDropDown'] = $sortDropDown;
}
$IPBHTML .= "test
<pagination>{$pagination}</pagination>
{$results}";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>