<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 24 May 2015 13:55:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_ucp_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['coreAttachments'] = array('attachmentThumbLocation','attachmentPost','attach','attachAlmostFull','hasAttachLimit','hasPagesTop','hasAttachments','attachmentMultiDelete','hasPagesBottom');
$this->_funcHooks['displayNameForm'] = array('dnameOkMessage','dnameFbUser');
$this->_funcHooks['emailPasswordChangeForm'] = array('hideMessageIfAdmin','emailIsAdmin','passFbUser','removeUser','removeUser2','removeUser3','removeUser4','emailIsNotAdmin');
$this->_funcHooks['field_entry'] = array('cfieldDesc','cfieldDesc');
$this->_funcHooks['membersFacebookConnect'] = array('fbShowStatus','fbSyncPic','fbSyncStatus','canUpdateStatus','fbSyncStatus','statusImportGroup','fbLastSync','pImgE','pCheckE','pImgPS','pCheckPS','pImgRS','pCheckRS','fbPassword','fbDefaultEmail','fbMismatch');
$this->_funcHooks['membersIgnoredUsersForm'] = array('ignoreMemberTopics','ignoreMemberSigs','ignoreGlobal','ignoreMemberPms','ignoreUserchats','hasChatRow','members','canSee','topPagination','hasChat','hasChatNone','bottomPagination','hasChatRowCheckbox');
$this->_funcHooks['membersProfileForm'] = array('isOurTimezone','timezones','monthSelected','months','daySelected','days','yearSelected','years','canUploadPhoto','dstError','doAutoDst','doManualDst','doManualDst','showComments','yesModComments','showLastVisitors','showFriends','yesModFriends','friendsEnabled','changeMemberTitle','birthdayFields','showProfileInfo','requiredCfields','optionalCfields');
$this->_funcHooks['membersSignatureForm'] = array('hasSignatureLimits','htmlModeOn','canUseHtml','disablelightbox');
$this->_funcHooks['membersTwitterConnect'] = array('tcHasPic','tcShowStatus','tcHasPic','tcLastSync','tcSyncPic','tcSyncStatus','tcSyncIStatus','statusImportGroup','tcSyncAboutMe','tcSyncBgImg','canBG','twitterPassword');
$this->_funcHooks['notificationsForm'] = array('hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','keyExists','groupKeys','isPrivateMsg','badConfig','isTopicsOrPosts','notifyGroupsList','isCoreNot','updateLastApp','newNotApp','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','hasconfignotify','hasconfigdisable','keyNotDone','notifyOther','allowAdminMails');
$this->_funcHooks['notificationsLog'] = array('hasReadNotify','hasReadNotify','categories','hasconfirm','hasnotifyerror','hasNotifications','hasNotifyForMod','notifications');
$this->_funcHooks['userCPTemplate'] = array('isSettings','isSettingsInactive','active_tab','tabs','tabsMenus_active','items','errors','has_max_upload','usercp_form','hasMoreThanOneTabClass','hasMoreThanOneTabSidebar','hasMoreThanOneTabClassContent','has_errors','didSave','submit_button','end_form');


}

/* -- coreAttachments --*/
function coreAttachments($info="",$pages="",$attachments) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['coreAttachments'] ) )
{
$count_1407f1ddbaa36ce3752b1fbf11c32b96 = is_array($this->functionData['coreAttachments']) ? count($this->functionData['coreAttachments']) : 0;
$this->functionData['coreAttachments'][$count_1407f1ddbaa36ce3752b1fbf11c32b96]['info'] = $info;
$this->functionData['coreAttachments'][$count_1407f1ddbaa36ce3752b1fbf11c32b96]['pages'] = $pages;
$this->functionData['coreAttachments'][$count_1407f1ddbaa36ce3752b1fbf11c32b96]['attachments'] = $attachments;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- displayNameForm --*/
function displayNameForm($form=array(),$error="",$okmessage="", $isFB=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['displayNameForm'] ) )
{
$count_ee94314e77e6243617a00fd01e3d91fc = is_array($this->functionData['displayNameForm']) ? count($this->functionData['displayNameForm']) : 0;
$this->functionData['displayNameForm'][$count_ee94314e77e6243617a00fd01e3d91fc]['form'] = $form;
$this->functionData['displayNameForm'][$count_ee94314e77e6243617a00fd01e3d91fc]['error'] = $error;
$this->functionData['displayNameForm'][$count_ee94314e77e6243617a00fd01e3d91fc]['okmessage'] = $okmessage;
$this->functionData['displayNameForm'][$count_ee94314e77e6243617a00fd01e3d91fc]['isFB'] = $isFB;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- emailPasswordChangeForm --*/
function emailPasswordChangeForm($txt, $_message, $isFB=false) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['emailPasswordChangeForm'] ) )
{
$count_497d87eb8328973af96fd06ef4399ee5 = is_array($this->functionData['emailPasswordChangeForm']) ? count($this->functionData['emailPasswordChangeForm']) : 0;
$this->functionData['emailPasswordChangeForm'][$count_497d87eb8328973af96fd06ef4399ee5]['txt'] = $txt;
$this->functionData['emailPasswordChangeForm'][$count_497d87eb8328973af96fd06ef4399ee5]['_message'] = $_message;
$this->functionData['emailPasswordChangeForm'][$count_497d87eb8328973af96fd06ef4399ee5]['isFB'] = $isFB;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_dropdown --*/
function field_dropdown($name="",$options="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_entry --*/
function field_entry($title="",$desc="",$content="",$id="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['field_entry'] ) )
{
$count_d2cb57e3bb9bbe7ff45990629e91e44f = is_array($this->functionData['field_entry']) ? count($this->functionData['field_entry']) : 0;
$this->functionData['field_entry'][$count_d2cb57e3bb9bbe7ff45990629e91e44f]['title'] = $title;
$this->functionData['field_entry'][$count_d2cb57e3bb9bbe7ff45990629e91e44f]['desc'] = $desc;
$this->functionData['field_entry'][$count_d2cb57e3bb9bbe7ff45990629e91e44f]['content'] = $content;
$this->functionData['field_entry'][$count_d2cb57e3bb9bbe7ff45990629e91e44f]['id'] = $id;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_textarea --*/
function field_textarea($name="",$value="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- field_textinput --*/
function field_textinput($name="",$value="") {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersFacebookConnect --*/
function membersFacebookConnect($fbuid, $fbUserData, $linkedMemberData, $perms) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersFacebookConnect'] ) )
{
$count_4bd790d867fd161acdf1a75b168a9dbe = is_array($this->functionData['membersFacebookConnect']) ? count($this->functionData['membersFacebookConnect']) : 0;
$this->functionData['membersFacebookConnect'][$count_4bd790d867fd161acdf1a75b168a9dbe]['fbuid'] = $fbuid;
$this->functionData['membersFacebookConnect'][$count_4bd790d867fd161acdf1a75b168a9dbe]['fbUserData'] = $fbUserData;
$this->functionData['membersFacebookConnect'][$count_4bd790d867fd161acdf1a75b168a9dbe]['linkedMemberData'] = $linkedMemberData;
$this->functionData['membersFacebookConnect'][$count_4bd790d867fd161acdf1a75b168a9dbe]['perms'] = $perms;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersIgnoredUsersForm --*/
function membersIgnoredUsersForm($members) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersIgnoredUsersForm'] ) )
{
$count_4ec77093e0cbb6e2ce8aeacf858330cb = is_array($this->functionData['membersIgnoredUsersForm']) ? count($this->functionData['membersIgnoredUsersForm']) : 0;
$this->functionData['membersIgnoredUsersForm'][$count_4ec77093e0cbb6e2ce8aeacf858330cb]['members'] = $members;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersProfileCustomize --*/
function membersProfileCustomize($options, $input, $errors) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersProfileForm --*/
function membersProfileForm($custom_fields='',$group_titles='',$day='',$mon='',$year='', $amEditor='', $times=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersProfileForm'] ) )
{
$count_0ce7734c584fd8f69254f29c86f54e2c = is_array($this->functionData['membersProfileForm']) ? count($this->functionData['membersProfileForm']) : 0;
$this->functionData['membersProfileForm'][$count_0ce7734c584fd8f69254f29c86f54e2c]['custom_fields'] = $custom_fields;
$this->functionData['membersProfileForm'][$count_0ce7734c584fd8f69254f29c86f54e2c]['group_titles'] = $group_titles;
$this->functionData['membersProfileForm'][$count_0ce7734c584fd8f69254f29c86f54e2c]['day'] = $day;
$this->functionData['membersProfileForm'][$count_0ce7734c584fd8f69254f29c86f54e2c]['mon'] = $mon;
$this->functionData['membersProfileForm'][$count_0ce7734c584fd8f69254f29c86f54e2c]['year'] = $year;
$this->functionData['membersProfileForm'][$count_0ce7734c584fd8f69254f29c86f54e2c]['amEditor'] = $amEditor;
$this->functionData['membersProfileForm'][$count_0ce7734c584fd8f69254f29c86f54e2c]['times'] = $times;
}
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- membersSignatureForm --*/
function membersSignatureForm($editor_html="",$sig_restrictions=array(),$signature='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersSignatureForm'] ) )
{
$count_ff9861c5c9a1219f3466f140ffb9af83 = is_array($this->functionData['membersSignatureForm']) ? count($this->functionData['membersSignatureForm']) : 0;
$this->functionData['membersSignatureForm'][$count_ff9861c5c9a1219f3466f140ffb9af83]['editor_html'] = $editor_html;
$this->functionData['membersSignatureForm'][$count_ff9861c5c9a1219f3466f140ffb9af83]['sig_restrictions'] = $sig_restrictions;
$this->functionData['membersSignatureForm'][$count_ff9861c5c9a1219f3466f140ffb9af83]['signature'] = $signature;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersSignatureFormError --*/
function membersSignatureFormError($form) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- membersTwitterConnect --*/
function membersTwitterConnect($isConnected, $twitterUser=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['membersTwitterConnect'] ) )
{
$count_33e0321f25efa29cb4bc6d9540ff18bb = is_array($this->functionData['membersTwitterConnect']) ? count($this->functionData['membersTwitterConnect']) : 0;
$this->functionData['membersTwitterConnect'][$count_33e0321f25efa29cb4bc6d9540ff18bb]['isConnected'] = $isConnected;
$this->functionData['membersTwitterConnect'][$count_33e0321f25efa29cb4bc6d9540ff18bb]['twitterUser'] = $twitterUser;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- notificationsForm --*/
function notificationsForm($config, $emailData) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['notificationsForm'] ) )
{
$count_b800d4c22248d23d0faf61e17801f792 = is_array($this->functionData['notificationsForm']) ? count($this->functionData['notificationsForm']) : 0;
$this->functionData['notificationsForm'][$count_b800d4c22248d23d0faf61e17801f792]['config'] = $config;
$this->functionData['notificationsForm'][$count_b800d4c22248d23d0faf61e17801f792]['emailData'] = $emailData;
}
$IPBHTML .= "test";
return $IPBHTML;
}

/* -- notificationsLog --*/
function notificationsLog($notifications, $error='', $pages='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['notificationsLog'] ) )
{
$count_1a64487a92f415f8c7af9c73c6c7865d = is_array($this->functionData['notificationsLog']) ? count($this->functionData['notificationsLog']) : 0;
$this->functionData['notificationsLog'][$count_1a64487a92f415f8c7af9c73c6c7865d]['notifications'] = $notifications;
$this->functionData['notificationsLog'][$count_1a64487a92f415f8c7af9c73c6c7865d]['error'] = $error;
$this->functionData['notificationsLog'][$count_1a64487a92f415f8c7af9c73c6c7865d]['pages'] = $pages;
}
$IPBHTML .= "<template>popoverNotifications</template>
<notifications>
	".$this->__f__7e791fb18aa7b4ba9a76e7157c4d9232($notifications,$error,$pages)."</notifications>";
return $IPBHTML;
}


function __f__7e791fb18aa7b4ba9a76e7157c4d9232($notifications, $error='', $pages='')
{
	$_ips___x_retval = '';
	$__iteratorCount = 0;
	foreach( $notifications as $notification )
	{
		
		$__iteratorCount++;
		$_ips___x_retval .= "
		<notification>
			<id>{$notification['notify_id']}</id>
			<url><![CDATA[{$notification['notify_url']}]]></url>
			<icon><![CDATA[{$notification['member']['pp_thumb_photo']}]]></icon>
			<text><![CDATA[{$notification['notify_title']}]]></text>
		</notification>
	
";
	}
	$_ips___x_retval .= '';
	unset( $__iteratorCount );
	return $_ips___x_retval;
}

/* -- showNotification --*/
function showNotification($notification) {
$IPBHTML = "";
$IPBHTML .= "test";
return $IPBHTML;
}

/* -- unsubscribed --*/
function unsubscribed() {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- userCPTemplate --*/
function userCPTemplate($current_tab, $html, $tabs, $current_area, $errors=array(), $hide_form=0, $maxUpload=0) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_ucp', $this->_funcHooks['userCPTemplate'] ) )
{
$count_be07a438ebf5cd2399d3b107bca59e9c = is_array($this->functionData['userCPTemplate']) ? count($this->functionData['userCPTemplate']) : 0;
$this->functionData['userCPTemplate'][$count_be07a438ebf5cd2399d3b107bca59e9c]['current_tab'] = $current_tab;
$this->functionData['userCPTemplate'][$count_be07a438ebf5cd2399d3b107bca59e9c]['html'] = $html;
$this->functionData['userCPTemplate'][$count_be07a438ebf5cd2399d3b107bca59e9c]['tabs'] = $tabs;
$this->functionData['userCPTemplate'][$count_be07a438ebf5cd2399d3b107bca59e9c]['current_area'] = $current_area;
$this->functionData['userCPTemplate'][$count_be07a438ebf5cd2399d3b107bca59e9c]['errors'] = $errors;
$this->functionData['userCPTemplate'][$count_be07a438ebf5cd2399d3b107bca59e9c]['hide_form'] = $hide_form;
$this->functionData['userCPTemplate'][$count_be07a438ebf5cd2399d3b107bca59e9c]['maxUpload'] = $maxUpload;
}
$IPBHTML .= "{$html}";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>