<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 24 May 2015 13:55:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_mod_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['mergePostForm'] = array('selectedpids','selectedpidsjs','dates','authors','uploads','hasSelectedPidsJs','mergepostsdates','mergepostsauthors','mergepostsattachments');
$this->_funcHooks['movePostForm'] = array('isGuest','posts','movepostserror','movepostsloop');
$this->_funcHooks['moveTopicsForm'] = array('topics','movetopicsloop');
$this->_funcHooks['pruneSplash'] = array('defaultselectedoption','types','prunecompletehtml','confirmprune');
$this->_funcHooks['splitPostForm'] = array('split_posts','splitpostsloop');
$this->_funcHooks['topicHistory'] = array('mod_logs','topicmodlogs');


}

/* -- deleteTopicForm --*/
function deleteTopicForm($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- editTopicTitle --*/
function editTopicTitle($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mergeMultiplePolls --*/
function mergeMultiplePolls($polls, $tids) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mergePostForm --*/
function mergePostForm($editor, $dates, $authors, $uploads, $seoTitle) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['mergePostForm'] ) )
{
$count_fd9fe22915f01e02db84de015e13ed31 = is_array($this->functionData['mergePostForm']) ? count($this->functionData['mergePostForm']) : 0;
$this->functionData['mergePostForm'][$count_fd9fe22915f01e02db84de015e13ed31]['editor'] = $editor;
$this->functionData['mergePostForm'][$count_fd9fe22915f01e02db84de015e13ed31]['dates'] = $dates;
$this->functionData['mergePostForm'][$count_fd9fe22915f01e02db84de015e13ed31]['authors'] = $authors;
$this->functionData['mergePostForm'][$count_fd9fe22915f01e02db84de015e13ed31]['uploads'] = $uploads;
$this->functionData['mergePostForm'][$count_fd9fe22915f01e02db84de015e13ed31]['seoTitle'] = $seoTitle;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- mergeTopicsForm --*/
function mergeTopicsForm($forum, $topic) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- movePostForm --*/
function movePostForm($forum, $topic, $posts, $error='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['movePostForm'] ) )
{
$count_478baed27846142898d1c60fed3c94f9 = is_array($this->functionData['movePostForm']) ? count($this->functionData['movePostForm']) : 0;
$this->functionData['movePostForm'][$count_478baed27846142898d1c60fed3c94f9]['forum'] = $forum;
$this->functionData['movePostForm'][$count_478baed27846142898d1c60fed3c94f9]['topic'] = $topic;
$this->functionData['movePostForm'][$count_478baed27846142898d1c60fed3c94f9]['posts'] = $posts;
$this->functionData['movePostForm'][$count_478baed27846142898d1c60fed3c94f9]['error'] = $error;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- moveTopicForm --*/
function moveTopicForm($forum, $topic, $forum_jump) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- moveTopicsForm --*/
function moveTopicsForm($forum, $jump_html, $topics) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['moveTopicsForm'] ) )
{
$count_f8faf320537771d7bdc522b2c70b5c07 = is_array($this->functionData['moveTopicsForm']) ? count($this->functionData['moveTopicsForm']) : 0;
$this->functionData['moveTopicsForm'][$count_f8faf320537771d7bdc522b2c70b5c07]['forum'] = $forum;
$this->functionData['moveTopicsForm'][$count_f8faf320537771d7bdc522b2c70b5c07]['jump_html'] = $jump_html;
$this->functionData['moveTopicsForm'][$count_f8faf320537771d7bdc522b2c70b5c07]['topics'] = $topics;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- pruneSplash --*/
function pruneSplash($forum="", $forums_html="", $confirm_data="", $complete_html="") {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['pruneSplash'] ) )
{
$count_c5747a7010cf1b90c1163f86b317ce5a = is_array($this->functionData['pruneSplash']) ? count($this->functionData['pruneSplash']) : 0;
$this->functionData['pruneSplash'][$count_c5747a7010cf1b90c1163f86b317ce5a]['forum'] = $forum;
$this->functionData['pruneSplash'][$count_c5747a7010cf1b90c1163f86b317ce5a]['forums_html'] = $forums_html;
$this->functionData['pruneSplash'][$count_c5747a7010cf1b90c1163f86b317ce5a]['confirm_data'] = $confirm_data;
$this->functionData['pruneSplash'][$count_c5747a7010cf1b90c1163f86b317ce5a]['complete_html'] = $complete_html;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- simplePage --*/
function simplePage($title="", $msg="") {
$IPBHTML = "";
$IPBHTML .= "<strong>{$title}</strong><br /> {$msg}";
return $IPBHTML;
}

/* -- softDeleteSplash --*/
function softDeleteSplash($forum, $tids=array(), $canHardDelete=false) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- softDeleteSplashPosts --*/
function softDeleteSplashPosts($forum, $topic, $pids=array(), $canHardDelete=false) {
$IPBHTML = "";
$IPBHTML .= "<!--no data in this master skin-->";
return $IPBHTML;
}

/* -- splitPostForm --*/
function splitPostForm($forum, $topic, $posts, $jump) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['splitPostForm'] ) )
{
$count_7692c5b4bb418388a313f42e559f6a8e = is_array($this->functionData['splitPostForm']) ? count($this->functionData['splitPostForm']) : 0;
$this->functionData['splitPostForm'][$count_7692c5b4bb418388a313f42e559f6a8e]['forum'] = $forum;
$this->functionData['splitPostForm'][$count_7692c5b4bb418388a313f42e559f6a8e]['topic'] = $topic;
$this->functionData['splitPostForm'][$count_7692c5b4bb418388a313f42e559f6a8e]['posts'] = $posts;
$this->functionData['splitPostForm'][$count_7692c5b4bb418388a313f42e559f6a8e]['jump'] = $jump;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- topicHistory --*/
function topicHistory($topic, $avg_post, $mod_logs=array()) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_mod', $this->_funcHooks['topicHistory'] ) )
{
$count_741c1c83c4a65bc26848cbafa3f947ed = is_array($this->functionData['topicHistory']) ? count($this->functionData['topicHistory']) : 0;
$this->functionData['topicHistory'][$count_741c1c83c4a65bc26848cbafa3f947ed]['topic'] = $topic;
$this->functionData['topicHistory'][$count_741c1c83c4a65bc26848cbafa3f947ed]['avg_post'] = $avg_post;
$this->functionData['topicHistory'][$count_741c1c83c4a65bc26848cbafa3f947ed]['mod_logs'] = $mod_logs;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- unsubscribeForm --*/
function unsubscribeForm($forum, $topic, $text) {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>