<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD 3         */
/* CACHE FILE: Skin set id: 3               */
/* CACHE FILE: Generated: Sun, 24 May 2015 13:55:24 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_global_comments_3 extends skinMaster{

/**
* Construct
*/
function __construct( ipsRegistry $registry )
{
	parent::__construct( $registry );
	

$this->_funcHooks = array();
$this->_funcHooks['comment'] = array('canEditNoPost','commentQueued','authorwarn','userIgnoredLang','hasauthormemid','hasauthormidclose','commentignored','moderateCheckbox','enableRep','hasQ','canReply','canEdit','canHide','canApprove','canDelete','hasReport','commentinitignored');
$this->_funcHooks['commentHidden'] = array('canEditNoPost','moderateCheckbox','canUnhide','canDelete');
$this->_funcHooks['commentsList'] = array('comments','comments_top','comments_bottom','hasCaptcha','guestName','allow_comments');
$this->_funcHooks['form'] = array('comment_errors','isEditing','guest_captcha');


}

/* -- comment --*/
function comment($r, $parent, $settings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['comment'] ) )
{
$count_b3c0cece33c20e7a11482f23222df836 = is_array($this->functionData['comment']) ? count($this->functionData['comment']) : 0;
$this->functionData['comment'][$count_b3c0cece33c20e7a11482f23222df836]['r'] = $r;
$this->functionData['comment'][$count_b3c0cece33c20e7a11482f23222df836]['parent'] = $parent;
$this->functionData['comment'][$count_b3c0cece33c20e7a11482f23222df836]['settings'] = $settings;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- commentHidden --*/
function commentHidden($r, $parent, $settings) {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentHidden'] ) )
{
$count_bf07350d31505a54d80c986f41add109 = is_array($this->functionData['commentHidden']) ? count($this->functionData['commentHidden']) : 0;
$this->functionData['commentHidden'][$count_bf07350d31505a54d80c986f41add109]['r'] = $r;
$this->functionData['commentHidden'][$count_bf07350d31505a54d80c986f41add109]['parent'] = $parent;
$this->functionData['commentHidden'][$count_bf07350d31505a54d80c986f41add109]['settings'] = $settings;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- commentsList --*/
function commentsList($comments, $settings, $pages, $parent, $preReply='') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['commentsList'] ) )
{
$count_f1999c7ce01bd1f9028158879ff1678b = is_array($this->functionData['commentsList']) ? count($this->functionData['commentsList']) : 0;
$this->functionData['commentsList'][$count_f1999c7ce01bd1f9028158879ff1678b]['comments'] = $comments;
$this->functionData['commentsList'][$count_f1999c7ce01bd1f9028158879ff1678b]['settings'] = $settings;
$this->functionData['commentsList'][$count_f1999c7ce01bd1f9028158879ff1678b]['pages'] = $pages;
$this->functionData['commentsList'][$count_f1999c7ce01bd1f9028158879ff1678b]['parent'] = $parent;
$this->functionData['commentsList'][$count_f1999c7ce01bd1f9028158879ff1678b]['preReply'] = $preReply;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- form --*/
function form($comment, $parent, $editor="", $settings, $errors="", $do='saveEdit') {
$IPBHTML = "";
if( IPSLib::locationHasHooks( 'skin_global_comments', $this->_funcHooks['form'] ) )
{
$count_19ce4fe4d4a5a2d893eb083bff01d037 = is_array($this->functionData['form']) ? count($this->functionData['form']) : 0;
$this->functionData['form'][$count_19ce4fe4d4a5a2d893eb083bff01d037]['comment'] = $comment;
$this->functionData['form'][$count_19ce4fe4d4a5a2d893eb083bff01d037]['parent'] = $parent;
$this->functionData['form'][$count_19ce4fe4d4a5a2d893eb083bff01d037]['editor'] = $editor;
$this->functionData['form'][$count_19ce4fe4d4a5a2d893eb083bff01d037]['settings'] = $settings;
$this->functionData['form'][$count_19ce4fe4d4a5a2d893eb083bff01d037]['errors'] = $errors;
$this->functionData['form'][$count_19ce4fe4d4a5a2d893eb083bff01d037]['do'] = $do;
}
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}

/* -- getEditJs --*/
function getEditJs() {
$IPBHTML = "";
$IPBHTML .= "<!-- NoData -->";
return $IPBHTML;
}


}


/*--------------------------------------------------*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>